theme: jekyll-theme-minimal
logo: 
title: Kirsten Miller
description: I am a senior Environmental Science and Biology double major at Colby College with an interest in data analysis and visualization. Here are some samples of my work, including data analysis and research-based projects.
navigation:
  - title: Setup
    url: setup
