theme: jekyll-theme-minimal
logo: 
title: Kirsten Miller
description: I am a recent graduate of Colby College with a Bachelor's Degree in Environmental Science and Biology who is interested in data analysis and visualization. Here are some samples of my work, including data analysis and research-based projects.
navigation:
  - title: Setup
    url: setup
